import React, { createContext, useContext, useState } from 'react';

export type Language = 'EN' | 'PT' | 'HI' | 'AR' | 'JA' | 'RU' | 'ES' | 'DE' | 'KO' | 'ZH' | 'FR' | 'TR';

interface Translations {
  [key: string]: {
    [key: string]: string;
  };
}

const translations: Translations = {
  EN: {
    trade: 'Trade',
    portfolio: 'Portfolio',
    markets: 'Markets',
    more: 'More',
    connectWallet: 'Connect Wallet',
    trending: 'TRENDING',
    top10: 'TOP 10',
    youSwap: 'You swap',
    youReceive: 'You receive',
    enterAmount: 'Enter an amount',
    swap: 'Swap',
    selectToken: 'Select token',
    searchToken: 'Search token by name',
    allNetworks: 'All Networks',
    popularTokens: 'Popular tokens',
    max: 'MAX',
    auto: 'Auto',
    details: 'details',
    routesAndMarkets: '{routes} Routes + {markets} Markets',
    minEstimatedOutput: 'Min. Estimated Output',
    afterSlippage: 'After Slippage ({value}%)',
    exchangeFee: 'Exchange Fee',
    networkFee: 'Network Fee',
    networkStatus: 'Network Status',
    network: 'Network',
    status: 'Status',
    tradingRewards: 'Trade on Sentium and earn BOOSTED Rewards until 10/10/25',
    top: 'Top',
    mostVisited: 'Most Visited',
    new: 'New',
    memes: 'Memes',
    ai: 'AI',
    chains: 'Chains',
    quickBuy: 'Quick Buy',
    token: 'Token',
    price: 'Price',
    change24h: '24h %',
    change7d: '7d %',
    volume24h: '24h Volume',
    marketCap: 'Market Cap',
    tvl: 'TVL',
    assetOversight: 'Asset Oversight',
    myWallets: 'My Wallets',
    receive: 'Receive',
    send: 'Send',
    archived: 'Archived',
    hello: 'Hello',
    totalBalance: 'Total Balance',
    biggestGainer: '24h Biggest Gainer',
    biggestLoser: '24h Biggest Loser',
    portfolioAge: 'Portfolio Age',
    addWallet: 'Add Wallet',
    active: 'Active',
    inactive: 'Inactive',
    securitySettings: 'Security Settings',
    enable2FA: 'Enable 2FA',
    recoveryPhrase: 'Recovery Phrase',
    view: 'View',
    selectAsset: 'Select Asset',
    receiveAddress: 'Receive Address',
    copy: 'Copy',
    reviewSend: 'Review Send',
    cancel: 'Cancel',
    next: 'Next',
    confirm: 'Confirm',
    noArchivedAssets: 'No archived assets found',
    noArchiveHistory: 'No archive history available',
    tokenName: 'Token Name',
    holding: 'Holding',
    holdingsAmount: 'Holdings Amount',
    actions: 'Actions',
    recentActivity: 'Recent Activity',
    viewAll: 'View All',
    completed: 'Completed',
    received: 'Received',
    sent: 'Sent',
    availableBalance: 'Available Balance',
    paste: 'Paste',
    processing: 'Processing',
    success: 'Success',
    failed: 'Failed',
    tokenVerification: 'Token Verification',
    unverifiedToken: 'Unverified Token',
    priceImpact: 'Price Impact',
    priceRate: 'Price Rate',
    insufficientBalance: 'Insufficient Balance',
    stayConnected: 'Stay Connected',
    joinCommunity: 'Join our community',
    documentation: 'Documentation',
    settings: 'Settings',
    appearance: 'Appearance',
    darkMode: 'Dark Mode',
    language: 'Language',
    notifications: 'Notifications',
    security: 'Security',
    disconnect: 'Disconnect',
    quickSwap: 'Quick Swap',
    slippageTolerance: 'Slippage Tolerance',
    transactionDeadline: 'Transaction Deadline',
    minutes: 'minutes',
    resetDefaults: 'Reset to defaults',
    saveSettings: 'Save Settings',
    liquiditySources: 'Liquidity Sources',
    enabled: 'enabled',
    disabled: 'disabled',
    smartRouting: 'Smart Routing',
    directRouteOnly: 'Direct Route Only'
  },
  ES: {
    trade: 'Comerciar',
    portfolio: 'Portafolio',
    markets: 'Mercados',
    more: 'Más',
    connectWallet: 'Conectar Billetera',
    trending: 'TENDENCIAS',
    top10: 'TOP 10',
    youSwap: 'Intercambias',
    youReceive: 'Recibes',
    enterAmount: 'Ingresa un monto',
    swap: 'Intercambiar',
    selectToken: 'Seleccionar token',
    searchToken: 'Buscar token por nombre',
    allNetworks: 'Todas las Redes',
    popularTokens: 'Tokens populares',
    max: 'MÁX',
    auto: 'Auto',
    details: 'detalles',
    routesAndMarkets: '{routes} Rutas + {markets} Mercados',
    minEstimatedOutput: 'Salida Mínima Estimada',
    afterSlippage: 'Después del Deslizamiento ({value}%)',
    exchangeFee: 'Comisión de Intercambio',
    networkFee: 'Comisión de Red',
    networkStatus: 'Estado de la Red',
    network: 'Red',
    status: 'Estado',
    tradingRewards: 'Opera en Sentium y gana Recompensas AUMENTADAS hasta el 10/10/24',
    top: 'Principal',
    mostVisited: 'Más Visitados',
    new: 'Nuevo',
    memes: 'Memes',
    ai: 'IA',
    chains: 'Cadenas',
    quickBuy: 'Compra Rápida',
    token: 'Token',
    price: 'Precio',
    change24h: '24h %',
    change7d: '7d %',
    volume24h: 'Volumen 24h',
    marketCap: 'Cap. de Mercado',
    tvl: 'TVL',
    assetOversight: 'Supervisión de Activos',
    myWallets: 'Mis Billeteras',
    receive: 'Recibir',
    send: 'Enviar',
    archived: 'Archivado',
    hello: 'Hola',
    totalBalance: 'Balance Total',
    biggestGainer: 'Mayor Ganancia 24h',
    biggestLoser: 'Mayor Pérdida 24h',
    portfolioAge: 'Edad del Portafolio',
    addWallet: 'Agregar Billetera',
    active: 'Activo',
    inactive: 'Inactivo',
    securitySettings: 'Configuración de Seguridad',
    enable2FA: 'Activar 2FA',
    recoveryPhrase: 'Frase de Recuperación',
    view: 'Ver',
    selectAsset: 'Seleccionar Activo',
    receiveAddress: 'Dirección de Recepción',
    copy: 'Copiar',
    reviewSend: 'Revisar Envío',
    cancel: 'Cancelar',
    next: 'Siguiente',
    confirm: 'Confirmar',
    noArchivedAssets: 'No hay activos archivados',
    noArchiveHistory: 'No hay historial de archivo',
    tokenName: 'Nombre del Token',
    holding: 'Tenencia',
    holdingsAmount: 'Monto de Tenencias',
    actions: 'Acciones',
    recentActivity: 'Actividad Reciente',
    viewAll: 'Ver Todo',
    completed: 'Completado',
    received: 'Recibido',
    sent: 'Enviado',
    availableBalance: 'Saldo Disponible',
    paste: 'Pegar',
    processing: 'Procesando',
    success: 'Éxito',
    failed: 'Fallido',
    tokenVerification: 'Verificación de Token',
    unverifiedToken: 'Token No Verificado',
    priceImpact: 'Impacto en el Precio',
    priceRate: 'Tasa de Cambio',
    insufficientBalance: 'Saldo Insuficiente',
    stayConnected: 'Mantente Conectado',
    joinCommunity: 'Únete a nuestra comunidad',
    documentation: 'Documentación',
    settings: 'Configuración',
    appearance: 'Apariencia',
    darkMode: 'Modo Oscuro',
    language: 'Idioma',
    notifications: 'Notificaciones',
    security: 'Seguridad',
    disconnect: 'Desconectar',
    quickSwap: 'Intercambio Rápido',
    slippageTolerance: 'Tolerancia al Deslizamiento',
    transactionDeadline: 'Plazo de Transacción',
    minutes: 'minutos',
    resetDefaults: 'Restablecer valores predeterminados',
    saveSettings: 'Guardar Configuración',
    liquiditySources: 'Fuentes de Liquidez',
    enabled: 'habilitado',
    disabled: 'deshabilitado',
    smartRouting: 'Enrutamiento Inteligente',
    directRouteOnly: 'Solo Ruta Directa'
  },
  JA: {
    trade: '取引',
    portfolio: 'ポートフォリオ',
    markets: 'マーケット',
    more: 'その他',
    connectWallet: 'ウォレット接続',
    trending: 'トレンド',
    top10: 'トップ10',
    youSwap: '交換する',
    youReceive: '受け取る',
    enterAmount: '金額を入力',
    swap: '交換',
    selectToken: 'トークンを選択',
    searchToken: 'トークン名で検索',
    allNetworks: 'すべてのネットワーク',
    popularTokens: '人気のトークン',
    max: '最大',
    auto: '自動',
    details: '詳細',
    routesAndMarkets: '{routes}ルート + {markets}マーケット',
    minEstimatedOutput: '最小推定出力',
    afterSlippage: 'スリッページ後 ({value}%)',
    exchangeFee: '取引手数料',
    networkFee: 'ネットワーク手数料',
    networkStatus: 'ネットワークステータス',
    network: 'ネットワーク',
    status: 'ステータス',
    tradingRewards: 'Sentiumで取引してBOOSTED報酬を獲得（10/10/24まで）',
    top: 'トップ',
    mostVisited: 'よく見られている',
    new: '新着',
    memes: 'ミーム',
    ai: 'AI',
    chains: 'チェーン',
    quickBuy: 'クイック購入',
    token: 'トークン',
    price: '価格',
    change24h: '24時間変動率',
    change7d: '7日間変動率',
    volume24h: '24時間取引高',
    marketCap: '時価総額',
    tvl: 'TVL',
    assetOversight: '資産概要',
    myWallets: 'マイウォレット',
    receive: '受け取り',
    send: '送信',
    archived: 'アーカイブ',
    hello: 'こんにちは',
    totalBalance: '合計残高',
    biggestGainer: '24時間最大上昇',
    biggestLoser: '24時間最大下落',
    portfolioAge: 'ポートフォリオ年齢',
    addWallet: 'ウォレットを追加',
    active: 'アクティブ',
    inactive: '非アクティブ',
    securitySettings: 'セキュリティ設定',
    enable2FA: '2要素認証を有効化',
    recoveryPhrase: 'リカバリーフレーズ',
    view: '表示',
    selectAsset: '資産を選択',
    receiveAddress: '受取アドレス',
    copy: 'コピー',
    reviewSend: '送信内容を確認',
    cancel: 'キャンセル',
    next: '次へ',
    confirm: '確認',
    noArchivedAssets: 'アーカイブされた資産はありません',
    noArchiveHistory: 'アーカイブ履歴はありません',
    tokenName: 'トークン名',
    holding: '保有',
    holdingsAmount: '保有額',
    actions: 'アクション',
    recentActivity: '最近のアクティビティ',
    viewAll: 'すべて表示',
    completed: '完了',
    received: '受取済み',
    sent: '送信済み',
    availableBalance: '利用可能残高',
    paste: '貼り付け',
    processing: '処理中',
    success: '成功',
    failed: '失敗',
    tokenVerification: 'トークン検証',
    unverifiedToken: '未検証トークン',
    priceImpact: '価格への影響',
    priceRate: '価格レート',
    insufficientBalance: '残高不足',
    stayConnected: '接続を維持',
    joinCommunity: 'コミュニティに参加',
    documentation: 'ドキュメント',
    settings: '設定',
    appearance: '外観',
    darkMode: 'ダークモード',
    language: '言語',
    notifications: '通知',
    security: 'セキュリティ',
    disconnect: '切断',
    quickSwap: 'クイックスワップ',
    slippageTolerance: 'スリッページ許容度',
    transactionDeadline: '取引期限',
    minutes: '分',
    resetDefaults: 'デフォルトにリセット',
    saveSettings: '設定を保存',
    liquiditySources: '流動性ソース',
    enabled: '有効',
    disabled: '無効',
    smartRouting: 'スマートルーティング',
    directRouteOnly: '直接ルートのみ'
  },
  ZH: {
    trade: '交易',
    portfolio: '投资组合',
    markets: '市场',
    more: '更多',
    connectWallet: '连接钱包',
    trending: '热门',
    top10: '前10名',
    youSwap: '你交换',
    youReceive: '你收到',
    enterAmount: '输入金额',
    swap: '交换',
    selectToken: '选择代币',
    searchToken: '按名称搜索代币',
    allNetworks: '所有网络',
    popularTokens: '热门代币',
    max: '最大',
    auto: '自动',
    details: '详情',
    routesAndMarkets: '{routes}路线 + {markets}市场',
    minEstimatedOutput: '最小估计输出',
    afterSlippage: '滑点后 ({value}%)',
    exchangeFee: '交易费',
    networkFee: '网络费',
    networkStatus: '网络状态',
    network: '网络',
    status: '状态',
    tradingRewards: '在Sentium交易并获得提升奖励，直到24年10月10日',
    top: '顶部',
    mostVisited: '最常访问',
    new: '新增',
    memes: '米姆',
    ai: '人工智能',
    chains: '链',
    quickBuy: '快速购买',
    token: '代币',
    price: '价格',
    change24h: '24小时%',
    change7d: '7天%',
    volume24h: '24小时成交量',
    marketCap: '市值',
    tvl: '总锁定价值',
    assetOversight: '资产概览',
    myWallets: '我的钱包',
    receive: '接收',
    send: '发送',
    archived: '已归档',
    hello: '你好',
    totalBalance: '总余额',
    biggestGainer: '24小时最大涨幅',
    biggestLoser: '24小时最大跌幅',
    portfolioAge: '投资组合年龄',
    addWallet: '添加钱包',
    active: '活跃',
    inactive: '不活跃',
    securitySettings: '安全设置',
    enable2FA: '启用双重认证',
    recoveryPhrase: '恢复短语',
    view: '查看',
    selectAsset: '选择资产',
    receiveAddress: '接收地址',
    copy: '复制',
    reviewSend: '审查发送',
    cancel: '取消',
    next: '下一步',
    confirm: '确认',
    noArchivedAssets: '没有已归档的资产',
    noArchiveHistory: '没有归档历史',
    tokenName: '代币名称',
    holding: '持有',
    holdingsAmount: '持有金额',
    actions: '操作',
    recentActivity: '最近活动',
    viewAll: '查看全部',
    completed: '已完成',
    received: '已收到',
    sent: '已发送',
    availableBalance: '可用余额',
    paste: '粘贴',
    processing: '处理中',
    success: '成功',
    failed: '失败',
    tokenVerification: '代币验证',
    unverifiedToken: '未验证代币',
    priceImpact: '价格影响',
    priceRate: '价格比率',
    insufficientBalance: '余额不足',
    stayConnected: '保持连接',
    joinCommunity: '加入我们的社区',
    documentation: '文档',
    settings: '设置',
    appearance: '外观',
    darkMode: '深色模式',
    language: '语言',
    notifications: '通知',
    security: '安全',
    disconnect: '断开连接',
    quickSwap: '快速交换',
    slippageTolerance: '滑点容差',
    transactionDeadline: '交易截止时间',
    minutes: '分钟',
    resetDefaults: '重置为默认值',
    saveSettings: '保存设置',
    liquiditySources: '流动性来源',
    enabled: '已启用',
    disabled: '已禁用',
    smartRouting: '智能路由',
    directRouteOnly: '仅直接路由'
  },
  PT: {
    trade: 'Negociar',
    portfolio: 'Portfólio',
    markets: 'Mercados',
    more: 'Mais',
    connectWallet: 'Conectar Carteira',
    trending: 'TENDÊNCIAS',
    top10: 'TOP 10',
    youSwap: 'Você troca',
    youReceive: 'Você recebe',
    enterAmount: 'Digite um valor',
    swap: 'Trocar',
    selectToken: 'Selecionar token',
    searchToken: 'Buscar token por nome',
    allNetworks: 'Todas as Redes',
    popularTokens: 'Tokens populares',
    max: 'MÁX',
    auto: 'Auto',
    details: 'detalhes',
    routesAndMarkets: '{routes} Rotas + {markets} Mercados',
    minEstimatedOutput: 'Saída Mínima Estimada',
    afterSlippage: 'Após Slippage ({value}%)',
    exchangeFee: 'Taxa de Câmbio',
    networkFee: 'Taxa de Rede',
    networkStatus: 'Status da Rede',
    network: 'Rede',
    status: 'Status',
    tradingRewards: 'Negocie na Sentium e ganhe Recompensas AUMENTADAS até 10/10/24',
    top: 'Topo',
    mostVisited: 'Mais Visitados',
    new: 'Novo',
    memes: 'Memes',
    ai: 'IA',
    chains: 'Chains',
    quickBuy: 'Compra Rápida',
    token: 'Token',
    price: 'Preço',
    change24h: '24h %',
    change7d: '7d %',
    volume24h: 'Volume 24h',
    marketCap: 'Cap. de Mercado',
    tvl: 'TVL',
    assetOversight: 'Visão Geral de Ativos',
    myWallets: 'Minhas Carteiras',
    receive: 'Receber',
    send: 'Enviar',
    archived: 'Arquivado',
    hello: 'Olá',
    totalBalance: 'Saldo Total',
    biggestGainer: 'Maior Alta 24h',
    biggestLoser: 'Maior Baixa 24h',
    portfolioAge: 'Idade do Portfólio',
    addWallet: 'Adicionar Carteira',
    active: 'Ativo',
    inactive: 'Inativo',
    securitySettings: 'Configurações de Segurança',
    enable2FA: 'Ativar 2FA',
    recoveryPhrase: 'Frase de Recuperação',
    view: 'Ver',
    selectAsset: 'Selecionar Ativo',
    receiveAddress: 'Endereço de Recebimento',
    copy: 'Copiar',
    reviewSend: 'Revisar Envio',
    cancel: 'Cancelar',
    next: 'Próximo',
    confirm: 'Confirmar',
    noArchivedAssets: 'Nenhum ativo arquivado',
    noArchiveHistory: 'Nenhum histórico de arquivo',
    tokenName: 'Nome do Token',
    holding: 'Posse',
    holdingsAmount: 'Valor das Posses',
    actions: 'Ações',
    recentActivity: 'Atividade Recente',
    viewAll: 'Ver Tudo',
    completed: 'Concluído',
    received: 'Recebido',
    sent: 'Enviado',
    availableBalance: 'Saldo Disponível',
    paste: 'Colar',
    processing: 'Processando',
    success: 'Sucesso',
    failed: 'Falhou',
    tokenVerification: 'Verificação de Token',
    unverifiedToken: 'Token Não Verificado',
    priceImpact: 'Impacto no Preço',
    priceRate: 'Taxa de Câmbio',
    insufficientBalance: 'Saldo Insuficiente',
    stayConnected: 'Mantenha-se Conectado',
    joinCommunity: 'Junte-se à nossa comunidade',
    documentation: 'Documentação',
    settings: 'Configurações',
    appearance: 'Aparência',
    darkMode: 'Modo Escuro',
    language: 'Idioma',
    notifications: 'Notificações',
    security: 'Segurança',
    disconnect: 'Desconectar',
    quickSwap: 'Troca Rápida',
    slippageTolerance: 'Tolerância de Slippage',
    transactionDeadline: 'Prazo da Transação',
    minutes: 'minutos',
    resetDefaults: 'Restaurar Padrões',
    saveSettings: 'Salvar Configurações',
    liquiditySources: 'Fontes de Liquidez',
    enabled: 'ativado',
    disabled: 'desativado',
    smartRouting: 'Roteamento Inteligente',
    directRouteOnly: 'Apenas Rota Direta'
  },
  HI: {
    trade: 'ट्रेड',
    portfolio: 'पोर्टफोलियो',
    markets: 'मार्केट्स',
    more: 'और',
    connectWallet: 'वॉलेट कनेक्ट करें',
    trending: 'ट्रेंडिंग',
    top10: 'टॉप 10',
    youSwap: 'आप स्वैप करें',
    youReceive: 'आप प्राप्त करें',
    enterAmount: 'राशि दर्ज करें',
    swap: 'स्वैप',
    selectToken: 'टोकन चुनें',
    searchToken: 'नाम से टोकन खोजें',
    allNetworks: 'सभी नेटवर्क',
    popularTokens: 'लोकप्रिय टोकन',
    max: 'अधिकतम',
    auto: 'स्वचालित',
    details: 'विवरण',
    routesAndMarkets: '{routes} मार्ग + {markets} बाजार',
    minEstimatedOutput: 'न्यूनतम अनुमानित आउटपुट',
    afterSlippage: 'स्लिपेज के बाद ({value}%)',
    exchangeFee: 'एक्सचेंज शुल्क',
    networkFee: 'नेटवर्क शुल्क',
    networkStatus: 'नेटवर्क स्थिति',
    network: 'नेटवर्क',
    status: 'स्थिति',
    tradingRewards: 'Sentium पर ट्रेड करें और 10/10/24 तक बढ़े हुए रिवार्ड्स पाएं',
    top: 'शीर्ष',
    mostVisited: 'सबसे अधिक देखे गए',
    new: 'नया',
    memes: 'मीम्स',
    ai: 'एआई',
    chains: 'चेन्स',
    quickBuy: 'त्वरित खरीद',
    token: 'टोकन',
    price: 'मूल्य',
    change24h: '24घं %',
    change7d: '7दि %',
    volume24h: '24घं वॉल्यूम',
    marketCap: 'मार्केट कैप',
    tvl: 'टीवीएल',
    assetOversight: 'एसेट ओवरसाइट',
    myWallets: 'मेरे वॉलेट',
    receive: 'प्राप्त करें',
    send: 'भेजें',
    archived: 'आर्काइव्ड',
    hello: 'नमस्ते',
    totalBalance: 'कुल बैलेंस',
    biggestGainer: '24घं का सबसे बड़ा गेनर',
    biggestLoser: '24घं का सबसे बड़ा लूजर',
    portfolioAge: 'पोर्टफोलियो आयु',
    addWallet: 'वॉलेट जोड़ें',
    active: 'सक्रिय',
    inactive: 'निष्क्रिय',
    securitySettings: 'सुरक्षा सेटिंग्स',
    enable2FA: '2FA सक्षम करें',
    recoveryPhrase: 'रिकवरी फ्रेज',
    view: 'देखें',
    selectAsset: 'एसेट चुनें',
    receiveAddress: 'प्राप्ति पता',
    copy: 'कॉपी',
    reviewSend: 'भेजने की समीक्षा करें',
    cancel: 'रद्द करें',
    next: 'अगला',
    confirm: 'पुष्टि करें',
    noArchivedAssets: 'कोई आर्काइव्ड एसेट नहीं',
    noArchiveHistory: 'कोई आर्काइव इतिहास नहीं',
    tokenName: 'टोकन नाम',
    holding: 'होल्डिंग',
    holdingsAmount: 'होल्डिंग्स राशि',
    actions: 'कार्रवाइयां',
    recentActivity: 'हाल की गतिविधि',
    viewAll: 'सभी देखें',
    completed: 'पूर्ण',
    received: 'प्राप्त',
    sent: 'भेजा गया',
    availableBalance: 'उपलब्ध बैलेंस',
    paste: 'पेस्ट',
    processing: 'प्रोसेसिंग',
    success: 'सफल',
    failed: 'विफल',
    tokenVerification: 'टोकन वेरिफिकेशन',
    unverifiedToken: 'अवेरिफाइड टोकन',
    priceImpact: 'मूल्य प्रभाव',
    priceRate: 'मूल्य दर',
    insufficientBalance: 'अपर्याप्त बैलेंस',
    stayConnected: 'जुड़े रहें',
    joinCommunity: 'हमारी कम्युनिटी में शामिल हों',
    documentation: 'डॉक्यूमेंटेशन',
    settings: 'सेटिंग्स',
    appearance: 'दिखावट',
    darkMode: 'डार्क मोड',
    language: 'भाषा',
    notifications: 'नोटिफिकेशन्स',
    security: 'सुरक्षा',
    disconnect: 'डिस्कनेक्ट',
    quickSwap: 'क्विक स्वैप',
    slippageTolerance: 'स्लिपेज टॉलरेंस',
    transactionDeadline: 'ट्रांजैक्शन डेडलाइन',
    minutes: 'मिनट',
    resetDefaults: 'डिफ़ॉल्ट रीसेट करें',
    saveSettings: 'सेटिंग्स सेव करें',
    liquiditySources: 'लिक्विडिटी सोर्स',
    enabled: 'सक्षम',
    disabled: 'अक्षम',
    smartRouting: 'स्मार्ट राउटिंग',
    directRouteOnly: 'केवल डायरेक्ट राउट'
  },
  AR: {
    trade: 'تداول',
    portfolio: 'المحفظة',
    markets: 'الأسواق',
    more: 'المزيد',
    connectWallet: 'ربط المحفظة',
    trending: 'الرائج',
    top10: 'أفضل 10',
    youSwap: 'تبادل',
    youReceive: 'تستلم',
    enterAmount: 'أدخل المبلغ',
    swap: 'تبادل',
    selectToken: 'اختر الرمز',
    searchToken: 'البحث عن الرمز بالاسم',
    allNetworks: 'جميع الشبكات',
    popularTokens: 'الرموز الشائعة',
    max: 'الحد الأقصى',
    auto: 'تلقائي',
    details: 'تفاصيل',
    routesAndMarkets: '{routes} مسارات + {markets} أسواق',
    minEstimatedOutput: 'الحد الأدنى للناتج المقدر',
    afterSlippage: 'بعد الانزلاق ({value}%)',
    exchangeFee: 'رسوم التبادل',
    networkFee: 'رسوم الشبكة',
    networkStatus: 'حالة الشبكة',
    network: 'الشبكة',
    status: 'الحالة',
    tradingRewards: 'تداول على Sentium واحصل على مكافآت معززة حتى 10/10/24',
    top: 'الأعلى',
    mostVisited: 'الأكثر زيارة',
    new: 'جديد',
    memes: 'ميمز',
    ai: 'الذكاء الاصطناعي',
    chains: 'السلاسل',
    quickBuy: 'شراء سريع',
    token: 'الرمز',
    price: 'السعر',
    change24h: 'التغير 24س %',
    change7d: 'التغير 7أ %',
    volume24h: 'الحجم 24س',
    marketCap: 'القيمة السوقية',
    tvl: 'إجمالي القيمة المقفلة',
    assetOversight: 'نظرة عامة على الأصول',
    myWallets: 'محافظي',
    receive: 'استلام',
    send: 'إرسال',
    archived: 'مؤرشف',
    hello: 'مرحباً',
    totalBalance: 'الرصيد الإجمالي',
    biggestGainer: 'أكبر رابح 24س',
    biggestLoser: 'أكبر خاسر 24س',
    portfolioAge: 'عمر المحفظة',
    addWallet: 'إضافة محفظة',
    active: 'نشط',
    inactive: 'غير نشط',
    securitySettings: 'إعدادات الأمان',
    enable2FA: 'تفعيل 2FA',
    recoveryPhrase: 'عبارة الاسترداد',
    view: 'عرض',
    selectAsset: 'اختر الأصل',
    receiveAddress: 'عنوان الاستلام',
    copy: 'نسخ',
    reviewSend: 'مراجعة الإرسال',
    cancel: 'إلغاء',
    next: 'التالي',
    confirm: 'تأكيد',
    noArchivedAssets: 'لا توجد أصول مؤرشفة',
    noArchiveHistory: 'لا يوجد سجل أرشيف',
    tokenName: 'اسم الرمز',
    holding: 'الحيازة',
    holdingsAmount: 'مبلغ الحيازات',
    actions: 'الإجراءات',
    recentActivity: 'النشاط الأخير',
    viewAll: 'عرض الكل',
    completed: 'مكتمل',
    received: 'مستلم',
    sent: 'مرسل',
    availableBalance: 'الرصيد المتاح',
    paste: 'لصق',
    processing: 'جاري المعالجة',
    success: 'نجاح',
    failed: 'فشل',
    tokenVerification: 'التحقق من الرمز',
    unverifiedToken: 'رمز غير متحقق',
    priceImpact: 'تأثير السعر',
    priceRate: 'معدل السعر',
    insufficientBalance: 'رصيد غير كافٍ',
    stayConnected: 'ابق على اتصال',
    joinCommunity: 'انضم إلى مجتمعنا',
    documentation: 'التوثيق',
    settings: 'الإعدادات',
    appearance: 'المظهر',
    darkMode: 'الوضع الداكن',
    language: 'اللغة',
    notifications: 'الإشعارات',
    security: 'الأمان',
    disconnect: 'قطع الاتصال',
    quickSwap: 'تبادل سريع',
    slippageTolerance: 'تحمل الانزلاق',
    transactionDeadline: 'موعد نهائي للمعاملة',
    minutes: 'دقائق',
    resetDefaults: 'إعادة تعيين الافتراضيات',
    saveSettings: 'حفظ الإعدادات',
    liquiditySources: 'مصادر السيولة',
    enabled: 'مفعل',
    disabled: 'معطل',
    smartRouting: 'التوجيه الذكي',
    directRouteOnly: 'المسار المباشر فقط'
  },
  RU: {
    trade: 'Торговля',
    portfolio: 'Портфолио',
    markets: 'Рынки',
    more: 'Ещё',
    connectWallet: 'Подключить Кошелек',
    trending: 'ТРЕНДЫ',
    top10: 'ТОП 10',
    youSwap: 'Вы обмениваете',
    youReceive: 'Вы получаете',
    enterAmount: 'Введите сумму',
    swap: 'Обмен',
    selectToken: 'Выбрать токен',
    searchToken: 'Поиск токена по имени',
    allNetworks: 'Все сети',
    popularTokens: 'Популярные токены',
    max: 'МАКС',
    auto: 'Авто',
    details: 'детали',
    routesAndMarkets: '{routes} Маршрутов + {markets} Рынков',
    minEstimatedOutput: 'Мин. Ожидаемый Вывод',
    afterSlippage: 'После Проскальзывания ({value}%)',
    exchangeFee: 'Комиссия Обмена',
    networkFee: 'Комиссия Сети',
    networkStatus: 'Статус Сети',
    network: 'Сеть',
    status: 'Статус',
    tradingRewards: 'Торгуйте на Sentium и получайте ПОВЫШЕННЫЕ Награды до 10/10/24',
    top: 'Топ',
    mostVisited: 'Самые Посещаемые',
    new: 'Новое',
    memes: 'Мемы',
    ai: 'ИИ',
    chains: 'Цепи',
    quickBuy: 'Быстрая Покупка',
    token: 'Токен',
    price: 'Цена',
    change24h: '24ч %',
    change7d: '7д %',
    volume24h: 'Объем 24ч',
    marketCap: 'Рыночная Кап.',
    tvl: 'TVL',
    assetOversight: 'Обзор Активов',
    myWallets: 'Мои Кошельки',
    receive: 'Получить',
    send: 'Отправить',
    archived: 'Архивировано',
    hello: 'Привет',
    totalBalance: 'Общий Баланс',
    biggestGainer: 'Наибольший Рост 24ч',
    biggestLoser: 'Наибольшее Падение 24ч',
    portfolioAge: 'Возраст Портфолио',
    addWallet: 'Добавить Кошелек',
    active: 'Активный',
    inactive: 'Неактивный',
    securitySettings: 'Настройки Безопасности',
    enable2FA: 'Включить 2FA',
    recoveryPhrase: 'Фраза Восстановления',
    view: 'Просмотр',
    selectAsset: 'Выбрать Актив',
    receiveAddress: 'Адрес Получения',
    copy: 'Копировать',
    reviewSend: 'Проверить Отправку',
    cancel: 'Отмена',
    next: 'Далее',
    confirm: 'Подтвердить',
    noArchivedAssets: 'Нет архивированных активов',
    noArchiveHistory: 'Нет истории архива',
    tokenName: 'Название Токена',
    holding: 'Держание',
    holdingsAmount: 'Сумма Держаний',
    actions: 'Действия',
    recentActivity: 'Недавняя Активность',
    viewAll: 'Показать Все',
    completed: 'Завершено',
    received: 'Получено',
    sent: 'Отправлено',
    availableBalance: 'Доступный Баланс',
    paste: 'Вставить',
    processing: 'Обработка',
    success: 'Успех',
    failed: 'Ошибка',
    tokenVerification: 'Проверка Токена',
    unverifiedToken: 'Непроверенный Токен',
    priceImpact: 'Влияние на Цену',
    priceRate: 'Курс Цены',
    insufficientBalance: 'Недостаточный Баланс',
    stayConnected: 'Оставайтесь на Связи',
    joinCommunity: 'Присоединяйтесь к нашему сообществу',
    documentation: 'Документация',
    settings: 'Настройки',
    appearance: 'Внешний Вид',
    darkMode: 'Темный Режим',
    language: 'Язык',
    notifications: 'Уведомления',
    security: 'Безопасность',
    disconnect: 'Отключить',
    quickSwap: 'Быстрый Обмен',
    slippageTolerance: 'Допуск Проскальзывания',
    transactionDeadline: 'Срок Транзакции',
    minutes: 'минут',
    resetDefaults: 'Сбросить Настройки',
    saveSettings: 'Сохранить Настройки',
    liquiditySources: 'Источники Ликвидности',
    enabled: 'включено',
    disabled: 'отключено',
    smartRouting: 'Умная Маршрутизация',
    directRouteOnly: 'Только Прямой Маршрут'
  },
  DE: {
    trade: 'Handel',
    portfolio: 'Portfolio',
    markets: 'Märkte',
    more: 'Mehr',
    connectWallet: 'Wallet verbinden',
    trending: 'TRENDING',
    top10: 'TOP 10',
    youSwap: 'Sie tauschen',
    youReceive: 'Sie erhalten',
    enterAmount: 'Betrag eingeben',
    swap: 'Tauschen',
    selectToken: 'Token auswählen',
    searchToken: 'Token nach Namen suchen',
    allNetworks: 'Alle Netzwerke',
    popularTokens: 'Beliebte Token',
    max: 'MAX',
    auto: 'Auto',
    details: 'Details',
    routesAndMarkets: '{routes} Routen + {markets} Märkte',
    minEstimatedOutput: 'Min. Geschätzter Output',
    afterSlippage: 'Nach Slippage ({value}%)',
    exchangeFee: 'Tauschgebühr',
    networkFee: 'Netzwerkgebühr',
    networkStatus: 'Netzwerkstatus',
    network: 'Netzwerk',
    status: 'Status',
    tradingRewards: 'Handeln Sie auf Sentium und erhalten Sie ERHÖHTE Belohnungen bis 10.10.24',
    top: 'Top',
    mostVisited: 'Meist Besucht',
    new: 'Neu',
    memes: 'Memes',
    ai: 'KI',
    chains: 'Chains',
    quickBuy: 'Schnellkauf',
    token: 'Token',
    price: 'Preis',
    change24h: '24h %',
    change7d: '7T %',
    volume24h: '24h Volumen',
    marketCap: 'Marktkapitalisierung',
    tvl: 'TVL',
    assetOversight: 'Asset-Übersicht',
    myWallets: 'Meine Wallets',
    receive: 'Empfangen',
    send: 'Senden',
    archived: 'Archiviert',
    hello: 'Hallo',
    totalBalance: 'Gesamtguthaben',
    biggestGainer: 'Größter Gewinner 24h',
    biggestLoser: 'Größter Verlierer 24h',
    portfolioAge: 'Portfolio-Alter',
    addWallet: 'Wallet hinzufügen',
    active: 'Aktiv',
    inactive: 'Inaktiv',
    securitySettings: 'Sicherheitseinstellungen',
    enable2FA: '2FA aktivieren',
    recoveryPhrase: 'Wiederherstellungsphrase',
    view: 'Ansehen',
    selectAsset: 'Asset auswählen',
    receiveAddress: 'Empfangsadresse',
    copy: 'Kopieren',
    reviewSend: 'Senden überprüfen',
    cancel: 'Abbrechen',
    next: 'Weiter',
    confirm: 'Bestätigen',
    noArchivedAssets: 'Keine archivierten Assets',
    noArchiveHistory: 'Keine Archivhistorie',
    tokenName: 'Token-Name',
    holding: 'Bestand',
    holdingsAmount: 'Bestandsmenge',
    actions: 'Aktionen',
    recentActivity: 'Letzte Aktivität',
    viewAll: 'Alle anzeigen',
    completed: 'Abgeschlossen',
    received: 'Empfangen',
    sent: 'Gesendet',
    availableBalance: 'Verfügbares Guthaben',
    paste: 'Einfügen',
    processing: 'Verarbeitung',
    success: 'Erfolg',
    failed: 'Fehlgeschlagen',
    tokenVerification: 'Token-Verifizierung',
    unverifiedToken: 'Nicht verifizierter Token',
    priceImpact: 'Preisauswirkung',
    priceRate: 'Preisrate',
    insufficientBalance: 'Unzureichendes Guthaben',
    stayConnected: 'Bleiben Sie verbunden',
    joinCommunity: 'Treten Sie unserer Community bei',
    documentation: 'Dokumentation',
    settings: 'Einstellungen',
    appearance: 'Erscheinungsbild',
    darkMode: 'Dunkelmodus',
    language: 'Sprache',
    notifications: 'Benachrichtigungen',
    security: 'Sicherheit',
    disconnect: 'Trennen',
    quickSwap: 'Schnelltausch',
    slippageTolerance: 'Slippage-Toleranz',
    transactionDeadline: 'Transaktionsfrist',
    minutes: 'Minuten',
    resetDefaults: 'Standardeinstellungen',
    saveSettings: 'Einstellungen speichern',
    liquiditySources: 'Liquiditätsquellen',
    enabled: 'aktiviert',
    disabled: 'deaktiviert',
    smartRouting: 'Smart Routing',
    directRouteOnly: 'Nur direkte Route'
  },
  KO: {
    trade: '거래',
    portfolio: '포트폴리오',
    markets: '마켓',
    more: '더 보기',
    connectWallet: '지갑 연결',
    trending: '트렌딩',
    top10: '톱 10',
    youSwap: '스왑',
    youReceive: '받기',
    enterAmount: '금액 입력',
    swap: '스왑',
    selectToken: '토큰 선택',
    searchToken: '토큰 이름으로 검색',
    allNetworks: '모든 네트워크',
    popularTokens: '인기 토큰',
    max: '최대',
    auto: '자동',
    details: '상세',
    routesAndMarkets: '{routes} 경로 + {markets} 마켓',
    minEstimatedOutput: '최소 예상 출력',
    afterSlippage: '슬리피지 후 ({value}%)',
    exchangeFee: '거래 수수료',
    networkFee: '네트워크 수수료',
    networkStatus: '네트워크 상태',
    network: '네트워크',
    status: '상태',
    tradingRewards: 'Sentium에서 거래하고 24년 10월 10일까지 부스트 리워드 받기',
    top: '상위',
    mostVisited: '가장 많이 방문',
    new: '신규',
    memes: '밈',
    ai: 'AI',
    chains: '체인',
    quickBuy: '빠른 구매',
    token: '토큰',
    price: '가격',
    change24h: '24시간 %',
    change7d: '7일 %',
    volume24h: '24시간 거래량',
    marketCap: '시가총액',
    tvl: 'TVL',
    assetOversight: '자산 개요',
    myWallets: '내 지갑',
    receive: '받기',
    send: '보내기',
    archived: '보관됨',
    hello: '안녕하세요',
    totalBalance: '총 잔액',
    biggestGainer: '24시간 최대 상승',
    biggestLoser: '24시간 최대 하락',
    portfolioAge: '포트폴리오 나이',
    addWallet: '지갑 추가',
    active: '활성',
    inactive: '비활성',
    securitySettings: '보안 설정',
    enable2FA: '2FA 활성화',
    recoveryPhrase: '복구 구문',
    view: '보기',
    selectAsset: '자산 선택',
    receiveAddress: '받는 주소',
    copy: '복사',
    reviewSend: '전송 검토',
    cancel: '취소',
    next: '다음',
    confirm: '확인',
    noArchivedAssets: '보관된 자산 없음',
    noArchiveHistory: '보관 내역 없음',
    tokenName: '토큰 이름',
    holding: '보유',
    holdingsAmount: '보유 금액',
    actions: '작업',
    recentActivity: '최근 활동',
    viewAll: '모두 보기',
    completed: '완료됨',
    received: '받음',
    sent: '보냄',
    availableBalance: '사용 가능한 잔액',
    paste: '붙여넣기',
    processing: '처리 중',
    success: '성공',
    failed: '실패',
    tokenVerification: '토큰 검증',
    unverifiedToken: '미검증 토큰',
    priceImpact: '가격 영향',
    priceRate: '가격 비율',
    insufficientBalance: '잔액 부족',
    stayConnected: '연결 유지',
    joinCommunity: '커뮤니티 참여',
    documentation: '문서',
    settings: '설정',
    appearance: '외관',
    darkMode: '다크 모드',
    language: '언어',
    notifications: '알림',
    security: '보안',
    disconnect: '연결 해제',
    quickSwap: '빠른 스왑',
    slippageTolerance: '슬리피지 허용치',
    transactionDeadline: '거래 기한',
    minutes: '분',
    resetDefaults: '기본값 복원',
    saveSettings: '설정 저장',
    liquiditySources: '유동성 소스',
    enabled: '활성화됨',
    disabled: '비활성화됨',
    smartRouting: '스마트 라우팅',
    directRouteOnly: '직접 경로만'
  },
  FR: {
    trade: 'Trader',
    portfolio: 'Portefeuille',
    markets: 'Marchés',
    more: 'Plus',
    connectWallet: 'Connecter le Portefeuille',
    trending: 'TENDANCES',
    top10: 'TOP 10',
    youSwap: 'Vous échangez',
    youReceive: 'Vous recevez',
    enterAmount: 'Entrer un montant',
    swap: 'Échanger',
    selectToken: 'Sélectionner un jeton',
    searchToken: 'Rechercher un jeton par nom',
    allNetworks: 'Tous les réseaux',
    popularTokens: 'Jetons populaires',
    max: 'MAX',
    auto: 'Auto',
    details: 'détails',
    routesAndMarkets: '{routes} Routes + {markets} Marchés',
    minEstimatedOutput: 'Sortie Min. Estimée',
    afterSlippage: 'Après Glissement ({value}%)',
    exchangeFee: "Frais d'échange",
    networkFee: 'Frais de réseau',
    networkStatus: 'État du réseau',
    network: 'Réseau',
    status: 'État',
    tradingRewards: "Tradez sur Sentium et gagnez des récompenses BOOSTÉES jusqu'au 10/10/24",
    top: 'Haut',
    mostVisited: 'Plus Visités',
    new: 'Nouveau',
    memes: 'Mèmes',
    ai: 'IA',
    chains: 'Chaînes',
    quickBuy: 'Achat Rapide',
    token: 'Jeton',
    price: 'Prix',
    change24h: '24h %',
    change7d: '7j %',
    volume24h: 'Volume 24h',
    marketCap: 'Cap. Marché',
    tvl: 'TVL',
    assetOversight: "Aperçu d'Actifs",
    myWallets: 'Mes Portefeuilles',
    receive: 'Recevoir',
    send: 'Envoyer',
    archived: 'Archivé',
    hello: 'Bonjour',
    totalBalance: 'Solde Total',
    biggestGainer: 'Plus Grand Gagnant 24h',
    biggestLoser: 'Plus Grand Perdant 24h',
    portfolioAge: 'Âge du Portefeuille',
    addWallet: 'Ajouter un Portefeuille',
    active: 'Actif',
    inactive: 'Inactif',
    securitySettings: 'Paramètres de Sécurité',
    enable2FA: 'Activer 2FA',
    recoveryPhrase: 'Phrase de Récupération',
    view: 'Voir',
    selectAsset: 'Sélectionner un Actif',
    receiveAddress: 'Adresse de Réception',
    copy: 'Copier',
    reviewSend: "Vérifier l'Envoi",
    cancel: 'Annuler',
    next: 'Suivant',
    confirm: 'Confirmer',
    noArchivedAssets: "Pas d'actifs archivés",
    noArchiveHistory: "Pas d'historique d'archive",
    tokenName: 'Nom du Jeton',
    holding: 'Détention',
    holdingsAmount: 'Montant des Détentions',
    actions: 'Actions',
    recentActivity: 'Activité Récente',
    viewAll: 'Voir Tout',
    completed: 'Terminé',
    received: 'Reçu',
    sent: 'Envoyé',
    availableBalance: 'Solde Disponible',
    paste: 'Coller',
    processing: 'Traitement',
    success: 'Succès',
    failed: 'Échec',
    tokenVerification: 'Vérification du Jeton',
    unverifiedToken: 'Jeton Non Vérifié',
    priceImpact: 'Impact sur le Prix',
    priceRate: 'Taux de Prix',
    insufficientBalance: 'Solde Insuffisant',
    stayConnected: 'Restez Connecté',
    joinCommunity: 'Rejoignez notre communauté',
    documentation: 'Documentation',
    settings: 'Paramètres',
    appearance: 'Apparence',
    darkMode: 'Mode Sombre',
    language: 'Langue',
    notifications: 'Notifications',
    security: 'Sécurité',
    disconnect: 'Déconnecter',
    quickSwap: 'Échange Rapide',
    slippageTolerance: 'Tolérance de Glissement',
    transactionDeadline: 'Délai de Transaction',
    minutes: 'minutes',
    resetDefaults: 'Réinitialiser les Paramètres',
    saveSettings: 'Sauvegarder les Paramètres',
    liquiditySources: 'Sources de Liquidité',
    enabled: 'activé',
    disabled: 'désactivé',
    smartRouting: 'Routage Intelligent',
    directRouteOnly: 'Route Directe Uniquement'
  },
  TR: {
    trade: 'İşlem',
    portfolio: 'Portföy',
    markets: 'Piyasalar',
    more: 'Daha Fazla',
    connectWallet: 'Cüzdan Bağla',
    trending: 'TREND',
    top10: 'İLK 10',
    youSwap: 'Takas ediyorsunuz',
    youReceive: 'Alıyorsunuz',
    enterAmount: 'Miktar girin',
    swap: 'Takas',
    selectToken: 'Token seç',
    searchToken: 'İsme göre token ara',
    allNetworks: 'Tüm Ağlar',
    popularTokens: 'Popüler tokenler',
    max: 'MAKS',
    auto: 'Otomatik',
    details: 'detaylar',
    routesAndMarkets: '{routes} Rota + {markets} Piyasa',
    minEstimatedOutput: 'Min. Tahmini Çıktı',
    afterSlippage: 'Kayma Sonrası ({value}%)',
    exchangeFee: 'Takas Ücreti',
    networkFee: 'Ağ Ücreti',
    networkStatus: 'Ağ Durumu',
    network: 'Ağ',
    status: 'Durum',
    tradingRewards: "Sentium'da işlem yapın ve 10/10/24'e kadar ARTTIRILMIŞ Ödüller kazanın",
    top: 'Üst',
    mostVisited: 'En Çok Ziyaret Edilen',
    new: 'Yeni',
    memes: 'Memeler',
    ai: 'Yapay Zeka',
    chains: 'Zincirler',
    quickBuy: 'Hızlı Alım',
    token: 'Token',
    price: 'Fiyat',
    change24h: '24s %',
    change7d: '7g %',
    volume24h: '24s Hacim',
    marketCap: 'Piyasa Değeri',
    tvl: 'TVL',
    assetOversight: 'Varlık Gözetimi',
    myWallets: 'Cüzdanlarım',
    receive: 'Al',
    send: 'Gönder',
    archived: 'Arşivlendi',
    hello: 'Merhaba',
    totalBalance: 'Toplam Bakiye',
    biggestGainer: '24s En Çok Kazandıran',
    biggestLoser: '24s En Çok Kaybettiren',
    portfolioAge: 'Portföy Yaşı',
    addWallet: 'Cüzdan Ekle',
    active: 'Aktif',
    inactive: 'Pasif',
    securitySettings: 'Güvenlik Ayarları',
    enable2FA: '2FA Etkinleştir',
    recoveryPhrase: 'Kurtarma Kelimesi',
    view: 'Görüntüle',
    selectAsset: 'Varlık Seç',
    receiveAddress: 'Alım Adresi',
    copy: 'Kopyala',
    reviewSend: 'Gönderimi İncele',
    cancel: 'İptal',
    next: 'İleri',
    confirm: 'Onayla',
    noArchivedAssets: 'Arşivlenmiş varlık yok',
    noArchiveHistory: 'Arşiv geçmişi yok',
    tokenName: 'Token Adı',
    holding: 'Tutulan',
    holdingsAmount: 'Tutulan Miktar',
    actions: 'İşlemler',
    recentActivity: 'Son Aktivite',
    viewAll: 'Tümünü Gör',
    completed: 'Tamamlandı',
    received: 'Alındı',
    sent: 'Gönderildi',
    availableBalance: 'Kullanılabilir Bakiye',
    paste: 'Yapıştır',
    processing: 'İşleniyor',
    success: 'Başarılı',
    failed: 'Başarısız',
    tokenVerification: 'Token Doğrulama',
    unverifiedToken: 'Doğrulanmamış Token',
    priceImpact: 'Fiyat Etkisi',
    priceRate: 'Fiyat Oranı',
    insufficientBalance: 'Yetersiz Bakiye',
    stayConnected: 'Bağlı Kalın',
    joinCommunity: 'Topluluğumuza Katılın',
    documentation: 'Dokümantasyon',
    settings: 'Ayarlar',
    appearance: 'Görünüm',
    darkMode: 'Karanlık Mod',
    language: 'Dil',
    notifications: 'Bildirimler',
    security: 'Güvenlik',
    disconnect: 'Bağlantıyı Kes',
    quickSwap: 'Hızlı Takas',
    slippageTolerance: 'Kayma Toleransı',
    transactionDeadline: 'İşlem Süresi',
    minutes: 'dakika',
    resetDefaults: 'Varsayılanlara Sıfırla',
    saveSettings: 'Ayarları Kaydet',
    liquiditySources: 'Likidite Kaynakları',
    enabled: 'etkin',
    disabled: 'devre dışı',
    smartRouting: 'Akıllı Yönlendirme',
    directRouteOnly: 'Sadece Direkt Rota'
  }
};

interface LanguageContextType {
  language: Language;
  setLanguage: (lang: Language) => void;
  t: (key: string, params?: Record<string, string | number>) => string;
}

const LanguageContext = createContext<LanguageContextType | undefined>(undefined);

export const LanguageProvider: React.FC<{ children: React.ReactNode }> = ({ children }) => {
  const [language, setLanguage] = useState<Language>('EN');

  const t = (key: string, params?: Record<string, string | number>): string => {
    let text = translations[language]?.[key] || translations['EN'][key] || key;
    
    if (params) {
      Object.entries(params).forEach(([key, value]) => {
        text = text.replace(`{${key}}`, String(value));
      });
    }
    
    return text;
  };

  return (
    <LanguageContext.Provider value={{ language, setLanguage, t }}>
      {children}
    </LanguageContext.Provider>
  );
};

export const useLanguage = () => {
  const context = useContext(LanguageContext);
  if (context === undefined) {
    throw new Error('useLanguage must be used within a LanguageProvider');
  }
  return context;
};